
# SPRING-CLOUD-SLEUTH
spring:
  application:
    name: killrvideo
    
 
# LOGGING
logging:
  level:
    org.springframework.web: ERROR
  pattern:
    level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
 
tracing:
  serviceName: killrvideo
  zipkin:
    enabled: true
    url: http://127.0.0.1:9411/api/v2/spans
 
       

# Custom 'killrvideo' keys App
killrvideo:

  application: 
    name: killrvideo
    instance: 
      id: 0
      
  grpc: 
    port: 8899
  
  threadpool:
    minThreads: 5
    maxThreads: 10
    ttlThreads: 60
    queueSize: 1000
  
  graph:
    timeout: 3000
    recommendation.name: killrvideo_video_recommendations
  
  services:
    comment:
     async: true 
    
  etcd:
    host: 10.0.75.1
    port: 2379
    
  cassandra:
    clustername: killrvideo
    mutation-error-log: /tmp/killrvideo-mutation-errors.log
    maxNumberOfTries: 10
    delayBetweenTries: 2
    